global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "auth-service"
    static_configs:
      - targets: [ "auth-service:8000" ]

  - job_name: "order-service"
    static_configs:
      - targets: [ "order-service:8000" ]

  - job_name: "payment-service"
    static_configs:
      - targets: [ "payment-service:8000" ]

  - job_name: "notification-service"
    static_configs:
      - targets: [ "notification-service:8000" ]

  - job_name: "cadvisor"
    static_configs:
      - targets: [ "cadvisor:8080" ]

  - job_name: "node-exporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]
